#定义应用端口号
server:
  port: 80

#配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///meeting?setTimezone=GMT%2B8
      username: root
      password: root
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  banner:
    image:
      location: classpath:/static/image/logo.png

#配置 Mybatis Plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#腾讯 SecretId/SecretKey
SecretId: 
SecretKey: 

#注册管理员密匙
adminCode: 12345
