#定义应用端口号
server:
  port: 80

#配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///meeting?setTimezone=Aisa/shanghai
      username: root
      password: root
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    enabled: true
    cache: false

#设置id使用数据库id自增
mybatis-plus:
  global-config:
    db-config:
      id-type: auto

#腾讯 SecretId/SecretKey
SecretId: AKIDYuznLcbJkunPkpc8NL2TcXEfpiLhncBT
SecretKey: 4sTosfBIBn7BxQddMozsWtymJZYGhrkM
